export const Genders = {
  MALE: "Male",
  FEMALE: "Female",
  TRANSGENDER_MALE: "Transgender Male",
  TRANSGENDER_FEMALE: "Transgender Female",
  NON_BINARY: "Non-Binary",
  GENDERQUEER: "Genderqueer",
  GENDERFLUID: "Genderfluid",
  AGENDER: "Agender",
  BIGENDER: "Bigender",
  TWO_SPIRIT: "Two-Spirit",
  GENDER_NONCONFORMING: "Gender Nonconforming",
  QUESTIONING: "Questioning",
  OTHER: "Other",
};
